name: Deploy Hakaton Alta Cafe

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,JWT_SECRET,DATABASE_URL,ADMIN_LOGIN,ADMIN_PASSWORD,ADMIN_NAME,ADMIN_EMAIL,SCANNER_LOGIN,SCANNER_PASSWORD,SCANNER_NAME
          script: |
            if [ ! -d "$HOME/HAKATON" ]; then
              echo "Pasta do projeto não encontrada. Realizando o Clone Mágico Inicial..."
              cd $HOME
              git clone -b dev https://github.com/MaurilioSemeao/hakaton-alta-cafe.git HAKATON
            fi
            cd $HOME/HAKATON
            git fetch origin
            git checkout dev
            git reset --hard origin/dev

            # Gerar .env a partir das Secrets do GitHub
            echo "POSTGRES_USER=$POSTGRES_USER" > .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            echo "DATABASE_URL=\"$DATABASE_URL\"" >> .env
            echo "JWT_SECRET=\"$JWT_SECRET\"" >> .env
            echo "ADMIN_LOGIN=\"$ADMIN_LOGIN\"" >> .env
            echo "ADMIN_PASSWORD=\"$ADMIN_PASSWORD\"" >> .env
            echo "ADMIN_NAME=\"$ADMIN_NAME\"" >> .env
            echo "ADMIN_EMAIL=\"$ADMIN_EMAIL\"" >> .env
            echo "SCANNER_LOGIN=\"$SCANNER_LOGIN\"" >> .env
            echo "SCANNER_PASSWORD=\"$SCANNER_PASSWORD\"" >> .env
            echo "SCANNER_NAME=\"$SCANNER_NAME\"" >> .env

            chmod +x deploy.sh
            ./deploy.sh
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          SCANNER_LOGIN: ${{ secrets.SCANNER_LOGIN }}
          SCANNER_PASSWORD: ${{ secrets.SCANNER_PASSWORD }}
          SCANNER_NAME: ${{ secrets.SCANNER_NAME }}
