name: Deploy Production (Main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USER_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          script: |
            if [ ! -d "$HOME/alta-cafe-prod" ]; then
              echo "Pasta de produção não encontrada. Realizando Clone Inicial..."
              cd $HOME
              git clone -b main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MaurilioSemeao/hakaton-alta-cafe.git alta-cafe-prod
            fi
            cd $HOME/alta-cafe-prod
            # Atualiza a URL do remote para garantir que o token seja usado no pull/fetch
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MaurilioSemeao/hakaton-alta-cafe.git
            git fetch origin
            git checkout main
            git reset --hard origin/main
            chmod +x deploy-prod.sh
            ./deploy-prod.sh
